### PR TITLE
Updates for the main ELevate page

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
While not specifically required, I would like to see ALT text added for the image that we're using to describe migration paths. While the image is significantly easier to consume, it reduces our website's accessibility. @sboldyreva would you be able to add that? if not, I can open an issue to get it added at a later date.

**Comment by sboldyreva** [comment]
@bennyvasquez added the ALT text which is more specific about the scheme picture

**Comment by codyro** [comment]
I think we need to evaluate the workflow when adding i18n strings. This is handled via Weblate which pushes to this repository. Since this has been updated Weblate has been failing to push translations as it's now behind:

```To github.com:AlmaLinux/almalinux.org.git
 ! [rejected]        master -> weblate (non-fast-forward)
error: failed to push some refs to 'github.com:AlmaLinux/almalinux.org.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 (1)```

I believe we should be modifying / adding strings via our Weblate project at: https://hosted.weblate.org/projects/almalinux/website-backend/.

@jonathanspw You setup this portion for production. Does this sound right?

**Comment by jonathanspw** [comment]
> I think we need to evaluate the workflow when adding i18n strings. This is handled via Weblate which pushes to this repository. Since this has been updated Weblate has been failing to push translations as it's now behind:
> 
> ```
> To github.com:AlmaLinux/almalinux.org.git
>  ! [rejected]        master -> weblate (non-fast-forward)
> error: failed to push some refs to 'github.com:AlmaLinux/almalinux.org.git'
> hint: Updates were rejected because a pushed branch tip is behind its remote
> hint: counterpart. Check out this branch and integrate the remote changes
> hint: (e.g. 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
>  (1)
> ```
> 
> I believe we should be modifying / adding strings via our Weblate project at: https://hosted.weblate.org/projects/almalinux/website-backend/.
> 
> @jonathanspw You setup this portion for production. Does this sound right?

We should have this sorted now.  Weblate will open PRs instead of trying to merge straight back into the repo.  The problem was from it pulling from master but pushing to weblate and they got out of sync.  This is no longer going to be an issue since weblate will work directly against master and PR changes :)

**Review by jonathanspw — APPROVED** [review]
Approved from weblate perspective.

**Comment by bennyvasquez** [comment]
Looks good to me, @sboldyreva! Thank you for the additions. Merging now! <3

**Pull request merged**
