### PR TITLE
Building Pantheon Desktop Environment blog post

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by sboldyreva** [comment]
@bennyvasquez @jaboutboul please review

**Comment by codyro** [comment]
For the lazy: https://pantheon-post-preview.almalinux-org-11c.pages.dev/blog/building-pantheon-for-almalinux-9/

Looks good to me. The portion under `Rebuilding packages` could maybe use a table with lines to make it more clear / less messy looking.

**Comment by jonathanspw** [comment]
> For the lazy: https://pantheon-post-preview.almalinux-org-11c.pages.dev/blog/building-pantheon-for-almalinux-9/
> 
> Looks good to me. The portion under `Rebuilding packages` could maybe use a table with lines to make it more clear / less messy looking.

agree with this.

**Comment by bennyvasquez** [comment]
@codyro @jonathanspw the MD IS [actually a table for that section.](https://github.com/AlmaLinux/almalinux.org/pull/174/files#diff-6a24b9979b5222aa82eb5e4aaee8b431da2e1655d585d707650b57f57d54c852R110) 

Based on what I'm reading [here](https://www.markdownguide.org/tools/hugo/) and [here](https://gohugo.io/getting-started/configuration-markup/), it seems like the config.yaml needs to be updated to enable additional formatting through goldmark. Do you agree? If so, I can try that and see if those adjustments make the tables render properly.

**Comment by codyro** [comment]
I think we should be able to modify the CSS for the tables to make it look a bit more legible.

**Comment by bennyvasquez** [comment]
@sboldyreva @codyro Done! I didn't realize it was actually rending in a table without the formatting. :D What do y'all think of this?

**Comment by sboldyreva** [comment]
@bennyvasquez Thank you! Looks much better now

**Comment by bennyvasquez** [comment]
Fixed! If you like it and you're okay with it, let's publish this today! You'll just need to update the publish date, and I think everything else is G2G.

**Comment by sboldyreva** [comment]
@bennyvasquez Thanks, updated

**Review by bennyvasquez — APPROVED** [review]
Congrats on your first Alma post, @sboldyreva!

**Pull request merged**
