### PR TITLE
Updated Commercial Support Layout

### LINKED ISSUE #563: Adjust the commercial support display
A while ago @sej7278 opened #449 to address how commercial sponsors are presented on the site. While that design suggestion wasn't adopted, the marketing SIG did start discussing the design there, and one of our folks brought up this idea:

I think we should adopt it and implement it, for sure. It's a much cleaner look, while remaining consistent with our branding. If we add additional commercial sponsors in the future, we will have to reconsider this display (since I think adding a fourth column here would be cumbersome, though we might be able to make it work), but for now I like it a lot.

### PR DESCRIPTION
**Pull request by garnetred**
This PR closes #563 . 

This combines the work from #593 with https://github.com/garnetred/almalinux.org/pull/1 by @sej7278 to update the layout of the commercial support display section on the homepage. 

Desktop view: 
image

### CODE REVIEW

**Comment by sej7278** [comment]
LGTM!

**Comment by bennyvasquez** [comment]
Sorry for my extreme delay here, friends, but this looks great! I'm going to merge this one and close #593. If that is a mistake or causes problems, let me know!

**Review by bennyvasquez — APPROVED** [review]
looks good here, and I'm not seeing anything broken anywhere else. https://db047e34.almalinux-org.pages.dev/

**Comment by sej7278** [comment]
Yikes it doesn't look good on mobile

**Comment by garnetred** [comment]
Sorry! I could have made it more clear in the draft PR that the mobile view wasn't done yet. I did take a look at the code to see how it could be implemented - I figured it should be pretty similar to the other two sections - but then wasn't quite sure how the mobile view worked in those two sections.

**Pull request merged**
