### PR TITLE
updating the blog template to include the new social image bit.

### PR DESCRIPTION
**Pull request by bennyvasquez**
@codyro everything look good to you?

### CODE REVIEW

**Comment by codyro** [comment]
Due to how we do images in blog posts (eg; `static/blog-images/` and not using _partials),_ you'll need to specify which image(s) you want to use with Open Graph by populating the `images[]` array to point to the actual image(s) instead of pointing to just the directory. 

So your example should be more explicit and point to the image(s) we want to use:

```yaml
images:
  - /blog-images/cody-is-a-tired-man.png
  - /blog-images/this-edible-is-staring-at-me.png
````

**Review by codyro — CHANGES_REQUESTED** [review]
References my comment above :)

**Comment by bennyvasquez** [comment]
@codyro are you suggesting that needs to be added somewhere? It's not clear.

**Comment by codyro** [comment]
> @codyro are you suggesting that needs to be added somewhere? It's not clear.

Whoops, I thought the portion I commented on was the front matter of an existing post. I'd consider populating the example with an example image for clarity, but that's all I have.

**Review by codyro — APPROVED** [review]

**Comment by bennyvasquez** [comment]
Good catch! I'll update that in another PR.

**Pull request merged**
