### PR TITLE
Replace LXD with Incus

### PR DESCRIPTION
**Pull request by pastalian**
Image server is starting to restrict LXD users. We should encourage our users to use Incus.

Fixes: #447

### CODE REVIEW

**Comment by bennyvasquez** [comment]
@pastalian @codyro @LKHN, where do we stand on this one? I remember a conversation starting somewhere, but I don't remember where we landed.

**Comment by codyro** [comment]
Elkhan and I discussed this a bit back. It was determined that we won't be changing everything Incus yet, however there may be merit to us packaging this and offering it as an alternative (Synergy perhaps). 

Context: https://chat.almalinux.org/almalinux/pl/8i9ryr9zofbxmeoij89ogwndfh

**Comment by pastalian** [comment]
I'm fine with that decision. I wish you would have shared that with me sooner though :wink:

**Comment by metalefty** [comment]
@codyro I can't see the chat link, perhaps is the channel private? Can you invite me if you don't mind if I see the channel?

**Comment by codyro** [comment]
> @codyro I can't see the chat link, perhaps is the channel private? Can you invite me if you don't mind if I see the channel?

I brought this up in the wrong channel when this PR was submitted; it should have been public from the get-go. 

The chat amounted to Incus being heavily Debian-focused, and Debian only recently accepted it as a project. At the time of the discussion, there were no packages (snap or otherwise) outside of that ecosystem, so adjusting the documentation/website right now wouldn't have made sense for us. 

We then briefly humored the idea of packaging it (EX, [Synergy](https://wiki.almalinux.org/repos/Synergy.html)) if there is a demand for it.

In the interim, we'll see how the project progresses/let the dust settle before suggesting users use it.

If @pastalian or @metalefty are interested, don't hesitate to request a package. That would be one step in making it easier for us to suggest users start using it over LXC.

**Pull request closed without merging**
