### PR TITLE
Update styling for code,pre blocks so they're not hideous

### PR DESCRIPTION
**Pull request by codyro**

### CODE REVIEW

**Comment by codyro** [comment]
These changes make it so contents wrapped in back ticks look readable.

Changes have been tested in FireFox, Chrome (Desktop, Mobile), and Safari (Desktop, Mobile).

Before (current): https://almalinux.org/blog/building-warpinator-for-almalinux/
After (this PR): https://inline-styling-tweaks.almalinux-org-11c.pages.dev/blog/building-warpinator-for-almalinux/

**Comment by bennyvasquez** [comment]
I like where we're going here! It looks like the code text is now bigger than the rest of the text. Probably want to bring that down. Too, it could do with less padding around the code-formatted text, I think.

**Comment by codyro** [comment]
Ah, that's because the highlighting uses `code`/`pre` blocks, and it's screwing with the style.

@mattlasheboro Help, I'm out of my depth 😅

**Comment by mattlasheboro** [comment]
[bundle.txt](https://github.com/AlmaLinux/almalinux.org/files/12819995/bundle.txt)

Uploaded a bundle.css file (the upload doesn't support CSS so I had to rename it to txt).

It lowers the padding on pre blocks to something more conservative, and adds a little bit of horizontal padding on the individual code blocks.

The font sizes still aren't exact, this is because we are using a monospace font that is different from the normal site font.  We could swap the pre and code blocks to using the default site font if we wanted to have sizes that were consistent.

**Comment by codyro** [comment]
> I'm not able to push directly to this PR, I feel like sending the file is the quickest solution?

You can if you push to my repo/branch in this PR. I can't make this change now, so go nuts :). 

Add more commits by pushing to the [inline-styling-tweaks](https://github.com/codyro/almalinux.org/tree/inline-styling-tweaks) branch on [codyro/almalinux.org](https://github.com/codyro/almalinux.org).

**Review by jonathanspw — APPROVED** [review]

**Pull request merged**
