### PR TITLE
Adding a blog post of openQA availability

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by sboldyreva** [comment]
@bennyvasquez @jaboutboul

**Review by bennyvasquez — CHANGES_REQUESTED** [review]
Only some slight english edits! I did add one line addressing that we would consider adding KVM support now that we're not tied to 1:1. If you're okay with the changes @sboldyreva and @LKHN, we'll publish this on Thursday.

**Comment by sboldyreva** [comment]
@bennyvasquez @LKHN I'm good with the changes

**Comment by LKHN** [comment]
@bennyvasquez @sboldyreva LGTM :+1:

**Review by bennyvasquez — APPROVED** [review]

**Comment by bennyvasquez** [comment]
I'll get this merged in tomorrow morning to get it published!

**Pull request merged**
