### PR TITLE
Added sponsorship levels to commercial support section.

### PR DESCRIPTION
**Pull request by sej7278**
Sponsorship level demonstrates community involvement/investment to potential customers of commercial support.

I checked it in responsive design mode this time :smile: 

sponsors

### CODE REVIEW

**Comment by sej7278** [comment]
Anyone want to review this?

**Comment by bennyvasquez** [comment]
Yup, it’s on my list, but not high priority. I’ll assign it to myself to make it more clear you haven’t been forgotten. :)

**Comment by sej7278** [comment]
thanks @bennyvasquez i thought maybe i'd missed a step with the PR :hugs:

**Comment by sej7278** [comment]
I probably won't make the core Sig call tomorrow but could you discuss this perhaps please?

**Comment by bennyvasquez** [comment]
Hey @sej7278! As I said last time we talked, I'm still trying to decide how I want this displayed. I don't like the idea of using the icon in this manner. I think I'd rather have the design match the pins that I made for each level ([Platinum](https://www.dropbox.com/scl/fi/dsv7q0hgpq3wkje9cqysu/Platinum-background-white-letters.png?rlkey=vjt7v1nwxocr5x1xlmnywfy26&dl=0), [Silver](https://www.dropbox.com/scl/fi/krk26nzjqvuxc0kbx6zwh/White-background-blue-letters.png?rlkey=hmqlb849qxw9akbw246iqq8fi&dl=0)) but I haven't yet had a chance to incorporate those design elements. I don't just want to use those images, because they include the logo and that makes far less sense when it's on our own website.

**Comment by bennyvasquez** [comment]
@sej7278 I'd like to see something more like [this](https://github.com/AlmaLinux/almalinux.org/commit/1bb46db4697b845752959891c7e60bbfc29e3126), but this breaks the responsiveness (and I couldn't figure out how to either add to your PR or submit the suggestions in a sane way). What do you think about that?

**Comment by sej7278** [comment]
@bennyvasquez i'm not keen to be honest - the silver sponsor has no "bubble" so looks like a bug, plus the 2 bubbles are different sizes. i like the "founding sponsor" idea

**Comment by bennyvasquez** [comment]
@sej7278 happy to take other suggestions, if you'd like! The lack of silver highlight wasn't meant to be final, and we could easily add a second box for the "founding sponsor" line, making them all the same size. The biggest problem for me here is that I don't want to use the AlmaLinux icon to indicate sponsorship level. If you have another icon that you'd like to use, and can incorporate something like the bars, I think that might satisfy both asks.

**Comment by sej7278** [comment]
I'm no designer but I originally thought of using star or medal emoji's. I wonder if we just do something simple like that, then revisit the bubbles later.

**Comment by sej7278** [comment]
How about a star icon?

image

**Comment by codyro** [comment]
> How about a star icon?
> 
> 
> 
> image
> 
> 

This looks like a rating of some kind. I don't think this is the right approach.

**Comment by codyro** [comment]
> How about using the bubbles with the official platinum/silver colour codes, removing the icons:
> 
> 
> 
> Screenshot From 2024-10-12 16-53-59
> 
> 

I personally like this direction much more.

**Review by bennyvasquez — APPROVED** [review]
Love it! https://654172ce.almalinux-org.pages.dev/

**Pull request merged**
