### PR TITLE
Adding SVG icons of `gray` and `black and white`

### PR DESCRIPTION
**Pull request by srbala**
Adding SVG icons of `gray` and `black and white` styles.

When working with AlmaLinux WSL, needed these styles. I derived them from color `icon.svg` with color change.

### CODE REVIEW

**Comment by Addvilz** [comment]
@srbala thanks for the update! Do you intend to use/link these icons somewhere?

**Comment by srbala** [comment]
Yes, We need to provide links for logos/icons for documentations and powered by reference. This is a start.

**Comment by Addvilz** [comment]
Alright, in that case I would suggest we move these into `/static/branding/` instead, because `/static/images` is mostly for WWW relevant assets.

And it might make sense to add all these there too (with somewhat decent URL friendly file names) https://www.dropbox.com/sh/neikds361khmm2q/AAAwM6M-J14y9QsMZpzGJL-5a?dl=0

**Comment by srbala** [comment]
Sounds like good plan, I'll update PR

**Comment by bennyvasquez** [comment]
@srbala Sorry for the extreme delay here, but I'm just taking a look and it seems like these are still in the images folder. Do you want to swap them over to the branding folder for us and add the additional images?

**Comment by srbala** [comment]
These will be additional, I'll move them to branding folder.

**Review by iseletsk — APPROVED** [review]

**Pull request merged**
