### PR TITLE
adding a Feb events recap blog post

### PR DESCRIPTION
**Pull request by bennyvasquez**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
I wish there was a way to limit the size of the images when embedding them, and center them in the page, but I think that's a CSS thing. 

Anywhoooooooo, testing UR: https://958218de.almalinux-org.pages.dev/blog/2024-02-29-feb-event-recap/

**Comment by codyro** [comment]
Haha! I was going over it and was going to suggest modifying the image sizes. 

Hugo can process images (I have yet to try this locally): https://gohugo.io/content-management/image-processing/. I can play with it tomorrow if you like.

Then, for the  pedantic change I always feel terrible about:

> here’s the link to the full playlist

to

> Here's the link to the full playlist

**Review by codyro — APPROVED** [review]
If you publish this before I can look into the images, I'll make a new issue/PR to fix them retroactively.

**Comment by bennyvasquez** [comment]
Thanks, @codyro! <3

**Pull request merged**
