### PR TITLE
increase width of blog content

### PR DESCRIPTION
**Pull request by jonathanspw**
600px wide is way too thin.  the rest of the site is limited to 1320px by the `.container` element so this PR makes the blog width also inherit that limit.

### CODE REVIEW

**Comment by codyro** [comment]
This isn't my forte so I'm not sure if this change will break anything. Do we know why it was set to `680px` initially? Does it affect how it renders on mobile?

**Comment by jonathanspw** [comment]
No clue why it was that slim.  It's still fully responsive on mobile.

**Review by codyro — APPROVED** [review]

**Comment by bennyvasquez** [comment]
@jonathanspw  Is there a preview link for this somewhere? I'm not seeing anything from our trust CloudFlare bot.

**Comment by jonathanspw** [comment]
> @jonathanspw Is there a preview link for this somewhere? I'm not seeing anything from our trust CloudFlare bot.

image

This is on a 2k screen so there's still a lot of blank space, but it looks a lot better.  Basically just brings the content width in line with the header/footer.

**Comment by bennyvasquez** [comment]
I don't love how this ends up looking on my laptop (running 2560 × 1600). Without a limit on the images for each post (especially the header images) they end up absolutely massive. We either need to just increase the limit to ~850px, or we need to set a limit for images in posts to 850px wide.

**Pull request merged**
