### PR TITLE
Adds Hardware Certification 

### PR DESCRIPTION
**Pull request by mattrandomnumber**

### CODE REVIEW

**Comment by mattlasheboro** [comment]
I should mention that you need to run pagefind to rebuild the search/filter index if you change the content files.

Instructions for this are at:

https://pagefind.app/docs/installation/

**Comment by codyro** [comment]
> I should mention that you need to run pagefind to rebuild the search/filter index if you change the content files.
> 
> 
> 
> Instructions for this are at:
> 
> 
> 
> https://pagefind.app/docs/installation/
> 
> 
> 
> 

@jonathanspw we need to make sure to add this to the CI once it's ready.

**Comment by jonathanspw** [comment]
I've managed to successfully start building on top of this locally and plugging in some real data.  Amazing work on this @mattrandomnumber

**Comment by codyro** [comment]
Thank you so much @mattrandomnumber. I'll keep saying it until I can snag you lunch :).

**Comment by jonathanspw** [comment]
Closing for #614

**Pull request closed without merging**
