### PR TITLE
Update Live Media and RPI versions

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
@sboldyreva since the links don't change, is there a reason to add versions here? I think it's probably better to keep them generic (thereby preventing us from having to update them in the future), unless there's a specific reason to update the version numbers.

**Comment by sboldyreva** [comment]
@bennyvasquez thought that specifying the exact version we have for the image might be better for users since some images still have lower version. Of course up to the Board's decision

**Comment by bennyvasquez** [comment]
Oh, it's not a board decision at all. In this case it's a Marketing SIG decision. If you're okay with committing to updating it every time we release a new version, I'm okay with it being more verbose!

**Comment by sboldyreva** [comment]
@bennyvasquez since I still update ISOs and other images, it's not a problem to update these at all! :)

**Review by bennyvasquez — APPROVED** [review]

**Pull request merged**
