### PR TITLE
Newsletter display improvements

### PR DESCRIPTION
**Pull request by bennyvasquez**
* add a float right until the page gets too small, then float left.
* replace the signup link with a button, 'cause it's nicer to look at.

### CODE REVIEW

**Comment by bennyvasquez** [comment]
https://a13a619b.almalinux-org.pages.dev/

**Comment by jonathanspw** [comment]
It seems to orient too far right for me.

image

I'm on a 2k resolution which could be why I see it and you don't?

**Comment by jonathanspw** [comment]
Actually I see on the live site it's pushed right too, the image is just also pushed far left.

Shouldn't we constrict it within the content width of the rest of the site?

**Comment by bennyvasquez** [comment]
Oh, you mean the text? We sure can! Lemme poke.

**Comment by codyro** [comment]
If this can wait for 2-3 hours I can use LambdaTest to go over it with a variety of browsers/resolutions to ensure no wonkiness.

**Comment by bennyvasquez** [comment]
Works for me!

**Comment by codyro** [comment]
I checked it on a handful of OS/browsers/resolutions, and it appears fine across the board 👍

**Review by codyro — APPROVED** [review]

**Pull request merged**
