### PR TITLE
Adding ELevate GPG key to the Security page

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
@sboldyreva The "AlmaLinux OS 8 #1" and "AlmaLinux OS 8 #2" aren't clear to me at a glance. Can we add some more context there (even if it's just a "valid prior to January 2024" or something like that), and perhaps a link to our blog post about the new one?

**Comment by sboldyreva** [comment]
@bennyvasquez how about placing more context in such a way?
image

**Comment by codyro** [comment]
> @bennyvasquez how about placing more context in such a way?
> 
> image
> 
> 

That makes it much clearer and provides the needed context. Looks great :).

**Review by codyro — APPROVED** [review]

**Comment by bennyvasquez** [comment]
@sboldyreva From a user experience perspective, I want the older one below the currently used one, with a larger visual queue that we aren't using that one anymore. If it's not clear what I mean, we can merge this one, and I can submit another PR with the adjustments.

**Comment by sboldyreva** [comment]
@bennyvasquez sure I can change the AlmaLinux 8 key order but not sure I get it how the "a larger visual queue that we aren't using that one anymore" part should look like

**Comment by bennyvasquez** [comment]
That'll do!

**Pull request merged**
